services:
  # A Docker web service
  - type: web
    name: fantasynba
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py